apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-spa-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/tasks-spa"
